image: node:18-bullseye-slim

stages:
    - deploy

pages:
    stage: deploy
    script:
        - npm install
        - npm run formatter
        - npm run validate_apps
        - npm run build
        - mv dist/ public/
    artifacts:
        paths:
            - public
    only:
        - main
